# You need to generate a Theme Access password from your Shopify admin
# Go to: Shopify Admin > Apps > Theme Access > Create password
development:
  # This should be a Theme Access password (starts with shptka_)
  # NOT your store admin password
  password: shptka_3881ff546262162931f899984b332589
  # Optional: If you want to work with an existing theme, add its ID here
  theme_id: "185232916854"
  store: zmyfkc-q4.myshopify.com
