# You need to generate a Theme Access password from your Shopify admin
# Go to: Shopify Admin > Apps > Theme Access > Create password
development:
  # This should be a Theme Access password (starts with shptka_)
  # NOT your store admin password
  password: shptka_2ee042aa4163acfc6b73b7a69d13cf14
  # Optional: If you want to work with an existing theme, add its ID here
  # theme_id: "123456789"
  store: 1v1e1w-nc.myshopify.com
