# You need to generate a Theme Access password from your Shopify admin
# Go to: Shopify Admin > Apps > Theme Access > Create password
development:
  # This should be a Theme Access password (starts with shptka_)
  # NOT your store admin password
  password: shptka_639110120edbeb3d453a555bc28ed7a7
  # Optional: If you want to work with an existing theme, add its ID here
  theme_id: "185232916854"
  store: zmyfkc-q4.myshopify.com
